DATA:
  TRAIN:
    SIM:
      ROOT_DIR: "/media/DATA/LINUX_DATA/v12_sample/training"
      SPLIT_FILE: "/media/DATA/LINUX_DATA/v12_sample/training_lists/all_train.txt"
      META_NAME: "meta.pkl"
      DEPTH_NAME: "depthL.png"
      LEFT_NAME: "0128_irL_kuafu_half.png"
      RIGHT_NAME: "0128_irR_kuafu_half.png"
      LEFT_PATTERN_NAME: "0128_irL_kuafu_half.png"
      RIGHT_PATTERN_NAME: "0128_irR_kuafu_half.png"
    REAL:
      ROOT_DIR: "/media/DATA/LINUX_DATA/rand_scenes/rand_scenes"
      SPLIT_FILE: "/media/DATA/LINUX_DATA/rand_scenes/train_list.txt"
      LEFT_NAME: "1024_irL_real_360.png"
      RIGHT_NAME: "1024_irR_real_360.png"
      LEFT_PATTERN_NAME: "1024_irL_real_360.png"
      RIGHT_PATTERN_NAME: "1024_irR_real_360.png"
  VAL:
    SIM:
      ROOT_DIR: "/media/DATA/LINUX_DATA/v12_sample/training"
      SPLIT_FILE: "/media/DATA/LINUX_DATA/v12_sample/training_lists/all_val.txt"
      META_NAME: "meta.pkl"
      DEPTH_NAME: "depthL.png"
      LEFT_NAME: "0128_irL_kuafu_half.png"
      RIGHT_NAME: "0128_irR_kuafu_half.png"
      LEFT_PATTERN_NAME: "0128_irL_kuafu_half.png"
      RIGHT_PATTERN_NAME: "0128_irR_kuafu_half.png"
  TEST:
    REAL:
      ROOT_DIR: "/media/DATA/LINUX_DATA/ICCV2021_Diagnosis/real_data_v10/"
      SPLIT_FILE: "/media/DATA/LINUX_DATA/ICCV2021_Diagnosis/real_data_v10/test_list_hand_sample.txt"
      META_NAME: "meta.pkl"
      DEPTH_NAME: "depthL.png"
      LEFT_NAME: "1024_irL_real.png"
      RIGHT_NAME: "1024_irR_real.png"
      LABEL_NAME: "irL_label_image.png"
#      NORMAL_NAME: "normalL.png"
      HEIGHT: 544
      WIDTH: 960
#    SIM:
#      ROOT_DIR: "/media/DATA/LINUX_DATA/activezero2/datasets/primv2_rdang_rdpat_rdenv_rdtable/"
#      SPLIT_FILE: "/media/DATA/LINUX_DATA/v12_sample/training_lists/all_val.txt"
#      META_NAME: "meta.pkl"
#      DEPTH_NAME: "depthL.png"
#      LEFT_NAME: "0128_irL_kuafu_half.png"
#      RIGHT_NAME: "0128_irR_kuafu_half.png"
#      HEIGHT: 544
#      WIDTH: 960
#    REAL:
#      ROOT_DIR: "/media/DATA/LINUX_DATA/rand_scenes/rand_scenes/"
#      SPLIT_FILE: "/media/DATA/LINUX_DATA/rand_scenes/rand_scenes/rand_test.txt"
#      LEFT_NAME: "1024_irL_real_360.png"
#      RIGHT_NAME: "1024_irR_real_360.png"
#      HEIGHT: 544
#      WIDTH: 960
#    SIM:
#      ROOT_DIR: "/media/DATA/LINUX_DATA/activezero2/datasets/ijrrobj_simtest_fixang_fixpat"
#      SPLIT_FILE: "/media/DATA/LINUX_DATA/ICCV2021_Diagnosis/real_data_v10/test_list_hand_sample.txt"
#      META_NAME: "meta.pkl"
#      DEPTH_NAME: "depthL.png"
#      LEFT_NAME: "0128_irL_kuafu_half.png"
#      RIGHT_NAME: "0128_irR_kuafu_half.png"
#      HEIGHT: 544
#      WIDTH: 960
MODEL_TYPE: "PSMNetRange"
PSMNetRange:
  MIN_DISP: 12
  MAX_DISP: 96
  NUM_DISP: 192
  SET_ZERO: False
OPTIMIZER:
  TYPE: "Adam"
  LR: 1e-4
LR_SCHEDULER:
  TYPE: 'StepLR'
  StepLR:
    step_size: 20000
    gamma: 0.7
TRAIN:
  BATCH_SIZE: 1
  NUM_WORKERS: 1
  LOG_PERIOD: 10
  CHECKPOINT_PERIOD: 5000
  MAX_TO_KEEP: 2
  MAX_ITER: 10000
VAL:
  BATCH_SIZE: 1
  NUM_WORKERS: 1
  PERIOD: 10
  LOG_PERIOD: 10
LOSS:
  SIM_REPROJ:
    WEIGHT: 0.01
  REAL_REPROJ:
    WEIGHT: 2.0
TEST:
  NUM_WORKERS: 0
  MAX_DISP: 128
#  WEIGHT: "/home/rayu/Projects/active_zero2/outputs/example_psmnetrange/model_100000_range_simonly.pth"
  WEIGHT: "/home/rayu/Projects/active_zero2/outputs/example_psmnetrange/model_085000.pth"
#  WEIGHT: "/home/rayu/Projects/active_zero2/outputs/example_psmnetrange/model_100000_realdisp.pth"
